function(link_llvm_libs target)
  foreach(LIB ${ARGN})
    target_include_directories(${target} SYSTEM PRIVATE ${LLVM_MAIN_INCLUDE_DIR})
    target_link_libraries(${target} PRIVATE ${LIB})
  endforeach()
endfunction()

add_subdirectory(sycl-ls)
if("${SYCL_USE_LIBCXX}" STREQUAL "${LLVM_LIBCXX_USED}")
  add_subdirectory(syclbin-dump)
else()
  message(WARNING "Base LLVM and SYCL not built with the same C++ STL implementation, not building syclbin-dump")
endif()

if (SYCL_ENABLE_XPTI_TRACING)
  if (UNIX)
    add_subdirectory(sycl-prof)
    add_subdirectory(sycl-trace)
    add_subdirectory(sycl-sanitize)
  endif()
endif()

